from app.services.text_service import predict_text

# 🔥 Test cases
texts = [
    "This is a normal human written sentence.",
    "Artificial intelligence is transforming the world rapidly.",
    "The quick brown fox jumps over the lazy dog.",
    "This essay was generated by an AI system to demonstrate its capabilities."
]

for text in texts:
    print("\nInput:", text)

    try:
        label, confidence = predict_text(text)
        print("Prediction:", label)
        print("Confidence:", confidence, "%")

    except Exception as e:
        print("❌ Error:", e)